version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    environment:
      - GEMINI_API_KEY
      - GOOGLE_PROJECT_ID
      - GOOGLE_SERVICE_ACCOUNT_KEY
      - GOOGLE_LOCATION
      - BACKEND_PORT